import path from 'path';

import type { ContactMessage } from '@models/ContactMessage';

export class ContactMessageBuilder {
  private contactMessage: ContactMessage = {
    name: 'Playwright Tester',
    email: 'playwright.contact@example.com',
    subject: 'Framework Contact Test',
    message: 'This is a contact form submission generated by the Playwright framework.',
    filePath: path.join(process.cwd(), 'test-data/files/contact-upload.txt')
  };

  static create(): ContactMessageBuilder {
    return new ContactMessageBuilder();
  }

  build(): ContactMessage {
    return { ...this.contactMessage };
  }
}
